//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class PlanTable
{
		public string sequence;
		public string number;
		public string batchId;
		public string workOrder;
		public string group;
		public string classes;
		public string startTime;
		public string endTime;
		public string workTime;
		public string wTUnit;
		public string output;
		public string optUnit;
		public string chestId;
		public string chestNum;
		public string cnUnit;
		public string saveTime;
		public string timeUnit;

		public PlanTable ()
		{
		sequence = "--";
		number = "--";
		batchId = "--";
		workOrder = "--";
		group = "--";
		classes = "--";
		startTime = "--";
		endTime = "--";
		workTime = "--";
		wTUnit = "时间";
		output = "--";
		optUnit = "公斤";
		chestId = "--";
		chestNum = "--";
		cnUnit = "公斤";
		saveTime = "--";
		timeUnit = "时间";

	}
}



