//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: com.hawk.core.model.enums.AloneState.proto
namespace com.hawk.core.model.enums
{
    [global::ProtoBuf.ProtoContract(Name=@"AloneState")]
    public enum AloneState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoneAlone", Value=1)]
      NoneAlone = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YesAlone", Value=2)]
      YesAlone = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoAlone", Value=3)]
      NoAlone = 3
    }
  
}